### PR TITLE
Fixed bug in reddit.rb that was causing reddit searches to fail.

### PR DESCRIPTION
**Pull request by geekspeed**
Reddit has a strict policy on rate limiting certain common APIs via the User-Agent attribute. See post here: https://github.com/reddit/reddit/wiki/API. Added a Search Option to set your own user-agent or go with the default. This gets around the 403 errors that were silently killing reddit searches.

### CODE REVIEW

**Comment by ahoernecke** [comment]
Hi, thanks for the submission. I don't really want to merge this in because the default user agent contains your username, which I don't think is appropriate default behavior. If you resubmit where the user-agent is not overridden at by default I can merge this in.

**Comment by geekspeed** [comment]
Unfortunately those are the rules (from the doc):

Change your client's User-Agent string to something unique and descriptive, including the target platform, a unique application identifier, a version string, and your username as contact information, in the following format:
<platform>:<app ID>:<version string> (by /u/<reddit username>)
Example: User-Agent: android:com.example.myredditapp:v1.2.3 (by /u/kemitche)
Many default User-Agents (like "Python/urllib" or "Java") are drastically limited to encourage unique and descriptive user-agent strings.
Including the version number and updating it as you build your application allows us to safely block old buggy/broken versions of your app.
NEVER lie about your user-agent. This includes spoofing popular browsers and spoofing other bots. We will ban liars with extreme prejudice.

Unless you would rather I substitute in some other text.

**Comment by ahoernecke** [comment]
Fair enough, but you are not going to be initiating all of the searches that all deployments of Scumblr perform, and I'm guessing you don't want the Reddit admins reaching out to you if there is a problem with someone else's Scumblr searches. The default should probably be the Ruby user-agent that is sent natively. If people are performing enough searches to be limited they should override the user agent with their own account info so the admins know the right place to reach out. Probably makes sense to add a link to the reddit policy in the description field for the user agent option.

**Comment by ahoernecke** [comment]
Good call, I feel like they must have made a change at some point because the search provider had been working previously. 

In that case it seems like the right solution would be making the user agent option required. I can also add some error handling that will at least log when the searches are being throttled.

**Pull request closed without merging**
