### PR TITLE
add Github search provider

### PR DESCRIPTION
**Pull request by mig5**
Just a basic Search Provider for searching Github repositories. Feel free to include. 

Sadly wanted to search Gists by term, but doesn't appear Github's API supports that.

Edit: Also included mysql2 gem in Gemfile - wasn't meant to be part of pull request, oops!

### CODE REVIEW

**Comment by sroberts** [comment]
Love to see this. :+1:

**Comment by rybolov** [comment]
Google "inurl:gist.github.com/project foo bar" or "site:www.github.com foo bar"







Michael Smith, CISSP-ISSEP
rybolov@ryzhe.ath.cx @rybolov
www.guerilla-ciso.com

----- Reply message -----

**Comment by mig5** [comment]
I tried the above but I couldn't get the Google Search provider to respect the site-specific check (the search provider calls siteSearch as a parameter but it doesn't seem to work). Might be a problem with my CSE I suppose.

**Comment by ahoernecke** [comment]
Hi @mig5,

Thanks for the submission, would you mind resubmiting this without the addition of the mysql gem?

Thanks!

**Comment by mig5** [comment]
@ahoernecke sure thing, apologies - new pull request available at https://github.com/Netflix/Scumblr/pull/40

**Pull request closed without merging**
