### PR TITLE
Fix crash when GitHub API rate limiting is not enabled

### PR DESCRIPTION
**Pull request by badraufran**
After trying to set up Scumblr for GitHub Enterprise, I ran into a problem when trying to do a "Github Code Search" task. The app would raise an exception and exit.

I was getting the following error
> Error: Unable to retrieve rate limit for Github!

My company's hosted GitHub Enterprise does not have rate limiting enabled. So the API call to check the rate limiting endpoint `"#{@github_api_endpoint}/rate_limit?...` would return a 404. The previous code catches the error and raises an exception.

My solution is to
- check what the message from the failed response body is
- if the message is "Rate limiting is not enabled.", I set `no_limit` to true
  - if `no_limit` is true, I ignore any sleeping behavior which was implemented to stay within any API rate limits
- otherwise I continue the original flow and raise an exception.

Let me know if you want me to change anything. I tried to stick to the existing coding conventions.

### CODE REVIEW

**Comment by sbehrens** [comment]
@bradbenvenuti Pull looks good to me, as I mentioned on gitter we're currently doing a major code refactor which adds a ton of new features to the tool.  I imagine we'll have that done in the next 2 weeks and merge in all those changes into Master.  

During that time I will merge your PR into master as well. 

Thanks for contributing!

-Scott

**Comment by sbehrens** [comment]
@ahoernecke This pull looks good, we can merge when we pull async-refactor back into master.

**Comment by badraufran** [comment]
Hey @sbehrens, got an update on the progress of your refactor?

**Comment by sbehrens** [comment]
Running tests, then I'll merge this in.

**Comment by sbehrens** [comment]
Tests pass, thanks again for the PR.

**Pull request merged**
